### ISSUE TITLE
Unsupported materialize-amd makes this project outdated

### ISSUE THREAD

**Issue by explorer2309** [Dania02525/durandal_starter_app_materialize#1]
I am trying to solve the problem of using materialize with require js using AMD, which you have done using a fork of materialize - materialize-amd. Some of the functionality of materialize like leanModal does not work with the forked version. And the materialize-amd project is not supported any more. See - https://github.com/max1011/materialize-AMD/issues/3

Do you have any other way of fixing the AMD problem? If not, could you please add a comment in the readme so that people like me don't build false hopes.

Thanks!

**Comment by Dania02525** [comment]
will do, thanks for bringing it to my attention!
